In [1]:
import numpy as np

#输入矩阵
# A = np.array([[1, 1/3, 1/2, 1/5],
#               [3, 1, 1/3, 1/2],
#               [2, 3, 1, 1/2],
#               [5, 2, 1/2, 1]])

A = np.array([[1, 1/5, 1/3, 1/7],
              [5, 1, 1/4, 1/3],
              [3, 4, 1, 1/3],
              [7, 3, 3, 1]])

#求解特征值即特征向量
lamda = np.linalg.eig(A)

for i in range(len(lamda[0])):
    print('特征值：{0}\n对应的特征向量：\n{1}\n'.format(lamda[0][i], np.transpose([lamda[1][:,i]])))

index = np.argmax(lamda[0])
lamda_max = np.real(lamda[0][index])
vector = lamda[1][:,index]

vector_final = np.transpose((np.real(vector)))

print('最大特征值为：{0}\n对应的特征向量：\n{1}'.format(lamda_max, vector_final))


特征值：(4.406219615205062+0j)
对应的特征向量：
[[-0.09629213+0.j]
 [-0.25790788+0.j]
 [-0.46975793+0.j]
 [-0.83877222+0.j]]

特征值：(-0.16142509306185443+1.3179222056827207j)
对应的特征向量：
[[ 0.07821608-0.05727732j]
 [-0.27111845-0.19589286j]
 [-0.17295434+0.62635379j]
 [ 0.67564047+0.j        ]]

特征值：(-0.16142509306185443-1.3179222056827207j)
对应的特征向量：
[[ 0.07821608+0.05727732j]
 [-0.27111845+0.19589286j]
 [-0.17295434-0.62635379j]
 [ 0.67564047-0.j        ]]

特征值：(-0.08336942908134953+0j)
对应的特征向量：
[[-0.05870155+0.j]
 [ 0.02872215+0.j]
 [-0.24139953+0.j]
 [ 0.96822282+0.j]]

最大特征值为：4.406219615205062
对应的特征向量：
[-0.09629213 -0.25790788 -0.46975793 -0.83877222]


In [2]:
a = [0.1894905,0.37176764,0.61372791,0.67023893]
b = [-0.09629213,-0.25790788,-0.46975793,-0.83877222]

In [3]:
np.divide(a, sum(a))

array([0.10269236, 0.20147551, 0.3326033 , 0.36322884])

In [4]:
np.divide(b, sum(b))

array([0.05791206, 0.15511109, 0.28252205, 0.50445481])