In [16]:
import cv2
import numpy as np

In [48]:
!python findflag.py

In [51]:
!python getHSV.py

In [5]:
img_bgr = cv2.imread('../findflag.jpg')                  # 读取彩色图像
img_hsv = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2HSV)      # 转化为 HSV 格式

In [8]:
thresh1 = np.array([0, 120, 120])                       # 目标红旗的低阈值
thresh2 = np.array([10, 255, 255]) 
img_flag = cv2.inRange(img_hsv, thresh1, thresh2) 
img_flag

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [12]:
!python lvbo.py

In [27]:
!python showImage.py

Traceback (most recent call last):
  File "showImage.py", line 23, in <module>
    box = cv2.minAreaRect(cnts_sort[0])                     # 选取包含最大面积的轮廓，并得出最小外接矩形
IndexError: list index out of range


In [45]:
img_bgr = cv2.imread('../../train/01/Images/01_0002.jpg')                  # 读取彩色图像
# img_bgr = cv2.imread('../findflag.jpg')                  # 读取彩色图像
img_hsv = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2HSV)      # 转化为 HSV 格式
thresh1 = np.array([0, 20, 20])                       # 目标红旗的低阈值
thresh2 = np.array([10, 255, 255])                      # 目标红旗的高阈值
img_flag = cv2.inRange(img_hsv, thresh1, thresh2)       # 获取红旗部分

In [46]:
img_morph = img_flag.copy()                             # 复制图像
cv2.erode(img_morph, (3,3), img_morph, iterations= 3)   # 腐蚀运算
cv2.dilate(img_morph, (3,3), img_morph, iterations= 3)  # 膨胀运算

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [47]:
cnts, _ = cv2.findContours(img_morph, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE) # 获取图像轮廓
cnts_sort = sorted(cnts, key= cv2.contourArea, reverse= True) # 将轮廓包含面积从大到小排列
# box = cv2.minAreaRect(cnts_sort[0])                     # 选取包含最大面积的轮廓，并得出最小外接矩形
# points = np.int0(cv2.boxPoints(box))                    # 获得该矩形的四个定点
cv2.findContours(img_morph, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

((), None)

In [36]:
img_morph

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)